name: Deploy Prebuild

on:
  push:
    branches:
      - develop  # This is just an example branch, change it based on your project's conventions.

jobs:
  deploy-prebuild:
    name: Deploy Prebuilt Frontend to Vercel
    runs-on: ubuntu-latest
    environment: Prebuild  # Change this based on your project's conventions.
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=prebuild --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts as Prebuilt to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
